### ISSUE TITLE
Is your PHP server running on VPN? (being a requirement rumoured)

### ISSUE THREAD

**Issue by kn9ts** [icrackthecode/MPESA-API#2]
Is your PHP server running in a VPN? (being a requirement rumoured)

**Comment by icrackthecode** [comment]
Yeah. However it not a requirement.

**Comment by kn9ts** [comment]
This is new info to me. Do they limit the transactions limits? Or it is not required for a experimental/test environment?

**Comment by icrackthecode** [comment]
Minimum amount is 10 KES. Limit remains the same as MPESA's limit on daily transactions(which i guess is 70,00 KES per transaction and only two are allowed last i checked). Unfortunately, mpesa don't have a sandbox environment the only way to test is by making a minimum transaction o 10 KES. However since the pay bill used in this API is registered to safaricom as a testing pay bill. Upon request, they can easily revert the transaction for you.

**Comment by kn9ts** [comment]
Ok. Understood. Thank you.

**Comment by kn9ts** [comment]
One more thing, do join the @nairobijs slack channel -- https://bit.ly/slack-nbi-js (it's a self-invite link) and if you have telegram you can find us here: https://telegram.me/nairobijs

**Comment by icrackthecode** [comment]
sure
